[ squash merge ] adds support for aqlm
nyunAI/nyuntam-text-generation pull request #4
Opened 2024-08-06 09:00 UTC by shwu-nyunai

adds support for aqlm + pv tuning

2024-08-06 10:27 UTC, Arnav0400 requested changes

2024-08-06 10:27 UTC, Arnav0400 commented on .gitmodules
> +	branch = pv-tuning
can we also fix the commit ID of the submodules, since all these libraries are updated frequently?

2024-08-06 10:27 UTC, Arnav0400 commented on core/dataset.py
> +        tokenizer.eos_token_id = 2
can we infer this using the tokenizer as every model has a different token

2024-08-06 10:27 UTC, Arnav0400 commented on quantization/aqlm/config.py
> +    wandb: bool = False
I am not sure if we should have a wandb integration, if yes how is the login handled, does this conflict with our logger?

2024-08-06 10:27 UTC, Arnav0400 commented on quantization/aqlm/config.py
> +    block_type: str = "LlamaDecoderLayer"
do we only support llama arch?

2024-08-06 10:27 UTC, Arnav0400 commented on requirements.txt
why are the other requirements commented out?

2024-08-06 10:27 UTC, Arnav0400 commented on quantization/aqlm/utils/tokenize_dataset.py
> +    tokenizer.pad_token = tokenizer.eos_token
this is true only for llama models, can we add a condition to only do this when pad token is None

2024-08-06 10:27 UTC, Arnav0400 commented on quantization/aqlm/utils/finetune.py
> +    tokenizer.pad_token = tokenizer.eos_token
add conditional

2024-08-06 10:33 UTC, shwu-nyunai commented on .gitmodules
> +	branch = pv-tuning
the commit ids are fixed with the git hash so it always refers to the commit id with which it was added as a submodule. same for all submodules.

2024-08-06 10:46 UTC, shwu-nyunai commented on quantization/aqlm/config.py
> +    wandb: bool = False
> how is the login handled

haven't tested it out but as long as wandb is logged-in 
- globally for local runtimes
- and the env variables are set in .env file in the nyuncli workspace (which gets mounted to the docker [as here](https://github.com/nyunAI/nyunzero-cli/blob/03f45562a5b80db3be8f8c4623e7bbcdf9f30831/zero/core/utils.py#L262) )
it should be working

At least that's what was happening in our experimentation stage. Also, wandb's logger is only triggered if it's installed. 

> does this conflict with our logger?

in my testing the logs were as expected
we can, for the time being, remove wandb from the recipes.

let me know your opinion.

2024-08-06 10:47 UTC, Akash-guna requested changes

2024-08-06 10:47 UTC, Akash-guna commented on quantization/aqlm/main.py
> +        # logger.info(f"Created AQLM instance with config: {self.config}")
This comment maybe removed

2024-08-06 10:47 UTC, Akash-guna commented on quantization/aqlm/config.py
> +# if __name__ == "__main__":
Are these Commented lines important

2024-08-06 10:48 UTC, Arnav0400 commented on quantization/aqlm/config.py
> +    wandb: bool = False
lets set wandb by default to false for now, we can pick it later

2024-08-06 10:49 UTC, shwu-nyunai commented on quantization/aqlm/config.py
> +    block_type: str = "LlamaDecoderLayer"
no, I think this stayed from the defaults in the parsers.
Llama and Phi3 works ootb ✅

2024-08-06 13:22 UTC, shwu-nyunai commented on core/dataset.py
> +        tokenizer.eos_token_id = 2
added a check to update only if not already set in the tokenizer.

2024-08-06 13:35 UTC, shwu-nyunai commented on quantization/aqlm/main.py
> +        # logger.info(f"Created AQLM instance with config: {self.config}")
cleaned in the fix commit.

2024-08-06 13:36 UTC, shwu-nyunai commented on quantization/aqlm/config.py
> +# if __name__ == "__main__":
no. forgot to clean.

2024-08-06 13:36 UTC, shwu-nyunai commented on quantization/aqlm/utils/finetune.py
> +    tokenizer.pad_token = tokenizer.eos_token
fixed in the revision commit.

2024-08-06 13:36 UTC, shwu-nyunai commented on quantization/aqlm/utils/tokenize_dataset.py
> +    tokenizer.pad_token = tokenizer.eos_token
fixed in the revision commit.

2024-08-06 13:37 UTC, shwu-nyunai commented on requirements.txt
uncommented.

2024-08-06 14:06 UTC, Akash-guna approved these changes

2024-08-07 04:35 UTC, Arnav0400 commented on quantization/aqlm/config.py
> +    block_type: str = "LlamaDecoderLayer"
is there any ways this argument can be updated via config?

2024-08-07 04:36 UTC, Arnav0400 commented on quantization/aqlm/config.py
> +    block_type: str = "LlamaDecoderLayer"
@shwu-nyunai

2024-08-07 04:41 UTC, shwu-nyunai commented on quantization/aqlm/config.py
> +    block_type: str = "LlamaDecoderLayer"
yes; block_type is updated from the config.

2024-08-07 07:21 UTC, merged